* Change Log
** 0.1.0 <2023-06-16 Fri>
Add ApiFetcher to make requests to the server.
** 0.2.0 <2023-06-16 Fri>
Add CityAPI to get information about city from the server.
** 0.2.1 <2023-06-16 Fri>
Add the city handler to have cities-list in bot's command list.
** 0.2.2 <2023-06-16 Fri>
Update docker-compose file to run src.main as package.
** 0.2.3 <2023-06-16 Fri>
Fix fetcher's send_json to make post a request and get a response.
** 0.3.0 <2023-06-17 Sat>
Add the config file for DotsBotApi.
** 0.4.0 <2023-06-17 Sat>
Add UserAPI for register new user.
** 0.4.1 <2023-06-17 Sat>
Add the CI/CD configuration.
** 0.4.2 <2023-06-17 Sat>
Fixed the CI/CD configuration.
** 0.4.3 <2023-06-17 Sat>
Fixed the CI/CD configuration by adding all deps.
** 0.5.0 <2023-06-20 Tue>
Add methods to select a city and return message.
** 0.5.1 <2023-06-20 Tue>
Add the handler to select a city.
** 0.6.0 <2023-06-20 Tue>
Add company methods to get the list and to select a company.
** 0.6.1 <2023-06-20 Tue>
Add the company handlers.
** 0.7.0 <2023-06-20 Tue>
Add the method to show the items by categories.
** 0.7.1 <2023-06-20 Tue>
Add the handler to show items.
** 0.8.0 <2023-06-20 Tue>
Add the methods to show cart items and to add an item to a cart.
** 0.8.1 <2023-06-20 Tue>
Add the handlers to show cart items and to add an item to a cart.
** 0.9.0 <2023-06-22 Thu>
Add method to send and get the order.
** 0.9.2 <2023-06-22 Thu>
Add the order handler.
** 0.9.5 <2023-07-10 Mon>
Refactor the listeners of the commands.
** 0.9.6 <2023-07-18 Tue>
Update the config class for the dots bot api.
** 0.9.7 <2023-07-18 Tue>
Update the README.
** 0.9.7 <2023-07-18 Tue>
Add the CHANGELOG.

